# Generated by Django 3.2.9 on 2021-12-03 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_alter_staffer_staffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thecompany', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='fax_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Личный телефон'),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='post',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='staffer',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='work_phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Рабочий телефон'),
        ),
    ]
