# Generated by Django 3.2.9 on 2021-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='staffer',
        ),
        migrations.AddField(
            model_name='staffer',
            name='company',
            field=models.ManyToManyField(related_name='staffers', to='catalog.Company', verbose_name='Сотрудники'),
        ),
    ]
